# Generated by Django 3.2 on 2021-09-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='deal_date',
        ),
    ]
