# Generated by Django 3.2 on 2021-09-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_remove_deal_deal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='ticker',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
